config/routes.rb
Rails.application.routes.draw do
  resources :larderdbs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "welcome#show"
  resources :larderdbs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
end

app/models/larderdb.rb
class Larderdb < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/food_controller.rb
class FoodController < ApplicationController

end

app/controllers/larderdbs_controller.rb
class LarderdbsController < ApplicationController
  before_action :set_larderdb, only: [:show, :edit, :update, :destroy]

  # GET /larderdbs
  # GET /larderdbs.json
  def index
    @larderdbs = Larderdb.all
  end

  # GET /larderdbs/1
  # GET /larderdbs/1.json
  def show
  end

  # GET /larderdbs/new
  def new
    @larderdb = Larderdb.new
  end

  # GET /larderdbs/1/edit
  def edit
  end

  # POST /larderdbs
  # POST /larderdbs.json
  def create
    @larderdb = Larderdb.new(larderdb_params)

    respond_to do |format|
      if @larderdb.save
        format.html { redirect_to @larderdb, notice: 'Larderdb was successfully created.' }
        format.json { render :show, status: :created, location: @larderdb }
      else
        format.html { render :new }
        format.json { render json: @larderdb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /larderdbs/1
  # PATCH/PUT /larderdbs/1.json
  def update
    respond_to do |format|
      if @larderdb.update(larderdb_params)
        format.html { redirect_to @larderdb, notice: 'Larderdb was successfully updated.' }
        format.json { render :show, status: :ok, location: @larderdb }
      else
        format.html { render :edit }
        format.json { render json: @larderdb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /larderdbs/1
  # DELETE /larderdbs/1.json
  def destroy
    @larderdb.destroy
    respond_to do |format|
      format.html { redirect_to larderdbs_url, notice: 'Larderdb was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_larderdb
      @larderdb = Larderdb.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def larderdb_params
      params.require(:larderdb).permit(:food, :nutrition)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show

  end
end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/larderdbs_helper.rb
module LarderdbsHelper
end

app/views/larderdbs/_form.html.erb
<%= form_with(model: larderdb, local: true) do |form| %>
  <% if larderdb.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(larderdb.errors.count, "error") %> prohibited this larderdb from being saved:</h2>

      <ul>
      <% larderdb.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :food %>
    <%= form.text_field :food %>
  </div>

  <div class="field">
    <%= form.label :nutrition %>
    <%= form.text_area :nutrition %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/larderdbs/edit.html.erb
<h1>Editing Larderdb</h1>

<%= render 'form', larderdb: @larderdb %>

<%= link_to 'Show', @larderdb %> |
<%= link_to 'Back', larderdbs_path %>

app/views/larderdbs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Larderdbs</h1>

<table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Nutrition</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @larderdbs.each do |larderdb| %>
      <tr>
        <td><%= larderdb.food %></td>
        <td><%= larderdb.nutrition %></td>
        <td><%= link_to 'Show', larderdb %></td>
        <td><%= link_to 'Edit', edit_larderdb_path(larderdb) %></td>
        <td><%= link_to 'Destroy', larderdb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Larderdb', new_larderdb_path %>

app/views/larderdbs/new.html.erb
<h1>New Larderdb</h1>

<%= render 'form', larderdb: @larderdb %>

<%= link_to 'Back', larderdbs_path %>

app/views/larderdbs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Food:</strong>
  <%= @larderdb.food %>
</p>

<p>
  <strong>Nutrition:</strong>
  <%= @larderdb.nutrition %>
</p>

<%= link_to 'Edit', edit_larderdb_path(@larderdb) %> |
<%= link_to 'Back', larderdbs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Larder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if signed_in? %>
        Signed in as: <%= current_user.email %>
        <%= button_to 'Sign out', sign_out_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign in', sign_in_path %>
      <% end %>
    </header>

    <section>
      <div id="flash">
        <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      </div>
      <%= yield %>
    </section>
  </body>
  </html>

app/views/welcome/show.html.erb
<h1>Welcome</h1>
<a href="http://localhost:3000/larderdbs">
   <button>Home</button>
</a>